//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Data.Export
{
    using System;
    using System.Collections.Generic;
    
    public partial class geneomedata_relationships
    {
        public int geneomedata_relationshipsid { get; set; }
        public int gdataid_parent { get; set; }
        public int gdataid_child { get; set; }
        public int createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
