//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Data.Export
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GenomeManagerData : DbContext
    {
        public GenomeManagerData()
            : base("name=GenomeManagerData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<app_settings> app_settings { get; set; }
        public virtual DbSet<chromosome_studyenvironments_globals> chromosome_studyenvironments_globals { get; set; }
        public virtual DbSet<chromosome_studyparticipants_globals> chromosome_studyparticipants_globals { get; set; }
        public virtual DbSet<coding> codings { get; set; }
        public virtual DbSet<coding_activities_ugs> coding_activities_ugs { get; set; }
        public virtual DbSet<coding_activities_ugs_modifiers> coding_activities_ugs_modifiers { get; set; }
        public virtual DbSet<coding_attributecategory> coding_attributecategory { get; set; }
        public virtual DbSet<coding_backups> coding_backups { get; set; }
        public virtual DbSet<coding_gdataid_outcomeid> coding_gdataid_outcomeid { get; set; }
        public virtual DbSet<coding_groups> coding_groups { get; set; }
        public virtual DbSet<coding_groups_items> coding_groups_items { get; set; }
        public virtual DbSet<coding_messages> coding_messages { get; set; }
        public virtual DbSet<coding_ns_stem_bendef> coding_ns_stem_bendef { get; set; }
        public virtual DbSet<coding_ns_stem_outcomes> coding_ns_stem_outcomes { get; set; }
        public virtual DbSet<coding_peinterrelationship_groups> coding_peinterrelationship_groups { get; set; }
        public virtual DbSet<coding_peinterrelationship_groups_items> coding_peinterrelationship_groups_items { get; set; }
        public virtual DbSet<coding_program_activities> coding_program_activities { get; set; }
        public virtual DbSet<coding_program_characteristics> coding_program_characteristics { get; set; }
        public virtual DbSet<coding_program_comments> coding_program_comments { get; set; }
        public virtual DbSet<coding_program_contexts> coding_program_contexts { get; set; }
        public virtual DbSet<coding_program_curriculum> coding_program_curriculum { get; set; }
        public virtual DbSet<coding_program_effects> coding_program_effects { get; set; }
        public virtual DbSet<coding_program_logistics> coding_program_logistics { get; set; }
        public virtual DbSet<coding_program_methods_and_dvs> coding_program_methods_and_dvs { get; set; }
        public virtual DbSet<coding_programs> coding_programs { get; set; }
        public virtual DbSet<coding_status> coding_status { get; set; }
        public virtual DbSet<coding_status_groups> coding_status_groups { get; set; }
        public virtual DbSet<coding_tags> coding_tags { get; set; }
        public virtual DbSet<fileattachment> fileattachments { get; set; }
        public virtual DbSet<geneomedata_relationships> geneomedata_relationships { get; set; }
        public virtual DbSet<genome_groups> genome_groups { get; set; }
        public virtual DbSet<genomedata> genomedatas { get; set; }
        public virtual DbSet<genomedata_extended_users> genomedata_extended_users { get; set; }
        public virtual DbSet<genomedata_import_history> genomedata_import_history { get; set; }
        public virtual DbSet<genomedata_stem> genomedata_stem { get; set; }
        public virtual DbSet<genomedata_v> genomedata_v { get; set; }
        public virtual DbSet<genome> genomes { get; set; }
        public virtual DbSet<helpcontent> helpcontents { get; set; }
        public virtual DbSet<helpcontent_tracking> helpcontent_tracking { get; set; }
        public virtual DbSet<imprint> imprints { get; set; }
        public virtual DbSet<imprint_task_order> imprint_task_order { get; set; }
        public virtual DbSet<master_organization> master_organization { get; set; }
        public virtual DbSet<master_outcome_list> master_outcome_list { get; set; }
        public virtual DbSet<master_universalgene_categories> master_universalgene_categories { get; set; }
        public virtual DbSet<master_universalgene_modifiers> master_universalgene_modifiers { get; set; }
        public virtual DbSet<master_universalgene_types> master_universalgene_types { get; set; }
        public virtual DbSet<mf_dashboard_searchhistory> mf_dashboard_searchhistory { get; set; }
        public virtual DbSet<mf_genomedataset_02> mf_genomedataset_02 { get; set; }
        public virtual DbSet<mf_genomedataset_02_summary> mf_genomedataset_02_summary { get; set; }
        public virtual DbSet<mf_genomedataset_top3_02_summary> mf_genomedataset_top3_02_summary { get; set; }
        public virtual DbSet<mf_genomedataset_top5_02> mf_genomedataset_top5_02 { get; set; }
        public virtual DbSet<next_in_queue_excludes> next_in_queue_excludes { get; set; }
        public virtual DbSet<notesketch> notesketches { get; set; }
        public virtual DbSet<notesketch_stem> notesketch_stem { get; set; }
        public virtual DbSet<notesketch_v> notesketch_v { get; set; }
        public virtual DbSet<number> numbers { get; set; }
        public virtual DbSet<powerbi_links> powerbi_links { get; set; }
        public virtual DbSet<rating> ratings { get; set; }
        public virtual DbSet<session> sessions { get; set; }
        public virtual DbSet<subscribe_genome_groups> subscribe_genome_groups { get; set; }
        public virtual DbSet<subscribe_genomes> subscribe_genomes { get; set; }
        public virtual DbSet<subscribe_organization> subscribe_organization { get; set; }
        public virtual DbSet<subscribe_organization_prep> subscribe_organization_prep { get; set; }
        public virtual DbSet<subscribe_outcome_list> subscribe_outcome_list { get; set; }
        public virtual DbSet<tracking> trackings { get; set; }
        public virtual DbSet<user_permissions> user_permissions { get; set; }
        public virtual DbSet<user_pinned> user_pinned { get; set; }
        public virtual DbSet<user_registration_codes> user_registration_codes { get; set; }
        public virtual DbSet<user_roles> user_roles { get; set; }
        public virtual DbSet<user_settings> user_settings { get; set; }
        public virtual DbSet<user_tasks> user_tasks { get; set; }
        public virtual DbSet<usergroup> usergroups { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<users_onefinalreport> users_onefinalreport { get; set; }
        public virtual DbSet<utility_missingfile_report> utility_missingfile_report { get; set; }
        public virtual DbSet<coding_list_ordering> coding_list_ordering { get; set; }
    }
}
